import { useState, useEffect } from "react";

function TypewriterText({ text, speed = 18 }) {
  const [displayed, setDisplayed] = useState("");

  useEffect(() => {
    setDisplayed("");
    if (!text) return;
    let i = 0;
    const id = setInterval(() => {
      setDisplayed(text.slice(0, i + 1));
      i++;
      if (i >= text.length) clearInterval(id);
    }, speed);
    return () => clearInterval(id);
  }, [text, speed]);

  return <span>{displayed}</span>;
}

export default function ResultPanel({ result, loading }) {
  if (loading) {
    return (
      <div className="result-section">
        <div className="card">
          <div className="card-header">
            <span className="card-icon">📊</span>
            <h2>Analysis Result</h2>
          </div>
          <div className="card-body">
            <div className="empty-state">
              <div className="empty-state-icon">⏳</div>
              <p>Running AI analysis…<br />This may take a few seconds.</p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (!result) {
    return (
      <div className="result-section">
        <div className="card">
          <div className="card-header">
            <span className="card-icon">📊</span>
            <h2>Analysis Result</h2>
          </div>
          <div className="card-body">
            <div className="empty-state">
              <div className="empty-state-icon">🩻</div>
              <p>Upload a chest X-ray and click Analyze to see results.</p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  const isPneumonia = result.label === "PNEUMONIA";
  const badgeClass  = isPneumonia ? "diagnosis-badge badge-pneumonia" : "diagnosis-badge badge-normal";
  const barClass    = isPneumonia ? "conf-bar pneumonia" : "conf-bar normal";
  const pct         = result.probability ?? 0;

  return (
    <div className="result-section">

      {/* ── Diagnosis Card ── */}
      <div className="card">
        <div className="card-header">
          <span className="card-icon">📊</span>
          <h2>Diagnosis</h2>
        </div>
        <div className="card-body">
          <span className={badgeClass}>
            {isPneumonia ? "⚠️" : "✅"} {result.label}
          </span>

          {/* Confidence bar */}
          <div className="confidence-row" style={{ marginTop: "1rem" }}>
            <span className="conf-label">Confidence</span>
            <div className="conf-bar-wrap">
              <div className={barClass} style={{ width: `${pct}%` }} />
            </div>
            <span className="conf-pct">{pct.toFixed(1)}%</span>
          </div>

          {/* Info grid */}
          <div className="info-grid">
            <div className="info-item">
              <div className="info-item-label">Location</div>
              <div className="info-item-value">
                {result.location === "N/A" ? "—" : result.location}
              </div>
            </div>
            <div className="info-item">
              <div className="info-item-label">Assessment</div>
              <div className="info-item-value" style={{ fontSize: "0.78rem" }}>
                {result.severity}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ── Grad-CAM Heatmap ── */}
      {result.heatmap_b64 && (
        <div className="card">
          <div className="card-header">
            <span className="card-icon">🗺️</span>
            <h2>Grad-CAM Heatmap</h2>
          </div>
          <div className="card-body" style={{ padding: "0" }}>
            <div className="heatmap-wrap">
              <img
                src={`data:image/png;base64,${result.heatmap_b64}`}
                alt="Grad-CAM heatmap overlay"
              />
              <div className="heatmap-caption">
                Highlighted regions indicate areas the model focused on to make its prediction.
                Warmer colors (red/yellow) = higher activation.
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ── Clinical Report ── */}
      {result.report && (
        <div className="card">
          <div className="card-header">
            <span className="card-icon">📋</span>
            <h2>AI Clinical Report</h2>
          </div>
          <div className="card-body">
            <div className="report-text">
              <TypewriterText text={result.report} speed={15} />
            </div>
            <p style={{ fontSize: "0.7rem", color: "var(--clr-subtle)", marginTop: "0.6rem" }}>
              Generated by RAG pipeline using retrieved radiology references via Groq LLM.
              For educational purposes only.
            </p>
          </div>
        </div>
      )}

    </div>
  );
}
